### ISSUE TITLE
No version colossalai==0.1.10 and version>0.2.0 gives  would results in AttributeError: type object 'ChunkManager' has no attribute 'search_chunk_size'

### ISSUE THREAD

**Issue by xwuShirley** [hpcaitech/OPT-Benchmark#15]
Dear authors,

thank you very much for giving the benchmark. I am currently having two issues:
(1) there is no installation of version 0.1.10, we can only install >0.2.0 using pip https://pypi.org/project/colossalai/

(2) if I installed version >0.2.0, and  run_opt_clm_colossalai_new.sh  it comes to the following error:
Traceback (most recent call last):
  File "run_clm_no_trainer_colossalai_new.py", line 628, in <module>
    main()
  File "run_clm_no_trainer_colossalai_new.py", line 372, in main
    chunk_size = ChunkManager.search_chunk_size(model, 2**32, 8)
AttributeError: type object 'ChunkManager' has no attribute 'search_chunk_size'
I wonder where this function goes? or if it's gone, what would be the chunk_size we should put here?

Many thanks :)
Great work on the benchmark

Best,
Xiaoxia

**Comment by xwuShirley** [comment]
it looks like this is the function
https://github.com/hpcaitech/ColossalAI/pull/1052/files
